risk-param-defaults:
  accounts:
    - Trader-V2-Alan
    - Trader-V2-Pralhad
    - Trader-V2-Sundar
    - Trader-V2-Mahi
  defaults:
    reward_factor: 0.0
    risk_reward_ratio: 1.0
    trail_sl_factor: 0.1
risk-params:
  accounts:
    - Trader-V2-Alan
    - Trader-V2-Pralhad
    - Trader-V2-Sundar
    - Trader-V2-Mahi
  defaults:
    reward_factor: 0.0
    risk_reward_ratio: 1.0
    trail_sl_factor: 0.1
  scrips:
    - scripName: NSE_BAJAJFINSV
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.2
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_BAJAJ_AUTO
      models:
        - name: trainer.strategies.gspcV2
          signal: 1
          reward_factor: 0.63
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_BAJFINANCE
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.02
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_DRREDDY
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.14
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_HDFCBANK
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.79
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_HEROMOTOCO
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.0
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_LTIM
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 1.22
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_NTPC
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.1
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_POWERGRID
      models:
        - name: trainer.strategies.rfcV2
          signal: 1
          reward_factor: 0.27
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_SUNPHARMA
      models:
        - name: trainer.strategies.gspcV2
          signal: 1
          reward_factor: 2.52
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_TATACONSUM
      models:
        - name: trainer.strategies.gspcV2
          signal: 1
          reward_factor: 1.97
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_ASIANPAINT
      models:
        - name: trainer.strategies.gspcV2
          signal: -1
          reward_factor: 1.16
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_BAJFINANCE
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: 0.45
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_GRASIM
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.05
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_HDFCBANK
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.18
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_INDUSINDBK
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: 0.02
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_ITC
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.07
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_LT
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.26
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_POWERGRID
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.24
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_TECHM
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.06
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_TITAN
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.17
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_UPL
      models:
        - name: trainer.strategies.gspcV2
          signal: -1
          reward_factor: 0.19
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
    - scripName: NSE_UPL
      models:
        - name: trainer.strategies.rfcV2
          signal: -1
          reward_factor: -0.15
          risk_reward_ratio: 0.8
          trail_sl_factor: 0.5
