risk-params:
  accounts:
    - Trader-V2-Alan
    - Trader-V2-Pralhad
    - Trader-V2-Sundar
    - Trader-V2-Mahi
  defaults:
    reward_factor: 0.0
    risk_reward_ratio: 1.2
  scrips:
    - scripName: NSE_APOLLOHOSP
      models:
        - name: trainer.strategies.gspcV2
          signal: 1
          reward_factor: 0.0
          risk_reward_ratio: 1.2
          accounts:
            - name: Trader-V2-Mahi
              reward_factor: 0.0
              risk_reward_ratio: 1.2
        - name: trainer.strategies.gspcV2
          signal: -1
          reward_factor: 0.0
          risk_reward_ratio: 1.2
          accounts:
            - name: Trader-V2-Mahi
              reward_factor: 0.0
              risk_reward_ratio: 1.2