postgres:
  username: trader
  password:
  host: postres.hostname.com
  port: 12345
  database: trader
  predicate: " WHERE ts= (
    SELECT MAX(ts)
    FROM symbol_data
    where symbol ='{symbol}' and timeframe = {tf}
    ) and symbol ='{symbol}' and timeframe = {tf}"
  symbol_table: public.symbol_data
  summary_table: t_training_result_summary

trading-view:
  username: username@gmail.com
  secret: topsecret

shoonya:
  Trader-V2-User:
    user: 'User'
    pwd: 'Password'
    vc: 'User_U'
    apikey: 'API-key'
    imei: 'abc1234'
    token: token
    expiry_date: 2023-01-01
